source: site.md
dest: site
parsers:
  mjs: "@js"
  js: "@js"
  cjs: "@js"
  py: "@py"
  yaml: "@yaml"
  json: "@json"
template: "custom"
options:
  theme: dark
  repo: https://github.com/axel669/lib.ipsen
  favicon: https://axel669.net/images/megaman-rounded.png
  opengraph:
    title: Ipsen
    description: A static site generator that aims to be simple and powerful.
    image: https://axel669.net/images/megaman-rounded.png
    themeColor: "#00EEEE"
